### ISSUE TITLE
Caja, Calc and Orca are not set as default applications

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint19.2-beta#54]
**Describe the bug**
In the preferred applications, the file manager and the Calc is empty, we need to manually choose Caja and Calc.

**To Reproduce**
1. Start MATE menu System - Preferences - Preferred applications
2. Select System and Accessibility tabs

**Expected behavior**
Caja, Calc and Orca should be set as default, they are not.

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**

- [ ] Cinnamon Edition
- [x] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [] Live session

**Screenshots**
![s](https://user-images.githubusercontent.com/3955499/61590825-a44a9d00-abbe-11e9-985b-4cd2470e7f51.png)

**Additional context**
These bugs are very old, only Onboard bug has been solved but now, a new bug with Calc appears :
https://github.com/mate-desktop/caja/issues/580
https://github.com/linuxmint/linuxmint/issues/52

**Comment by clefebvre** [comment]
Fixed for caja and calc.

I believe it's up to orca to deliver a desktop file or for MATE to adapt to the lack of one though.

**Comment by InfoLibre** [comment]
I made a bug report on https://github.com/mate-desktop/caja/issues/580 but all the bug reports I made on MATE were closed and not solved :o(
I begin to be tired of making bug reports without results.
But thank you to have solved the bug with Caja and Calc.

**Comment by InfoLibre** [comment]
I made a bugreport on https://gitlab.gnome.org/GNOME/orca/issues/55

**Comment by InfoLibre** [comment]
Orca answered me to contact Linux Mint or Ubuntu :o(
https://gitlab.gnome.org/GNOME/orca/issues/55

**Comment by gm10** [comment]
I'm not sure there's value in explaining to you that you've been barking up the wrong trees all these years because it has already been explained to you quite clearly in all the linked reports yet you seem to be (quite rudely) ignoring that. These aren't bugs with the packages you listed, but with the distribution alone, i.e. Linux Mint. For orca probably not your fault because of what Clem said above, so let me clarify that one:

Orca intentionally doesn't have a regular desktop file, it's up to the distribution to provide one:
https://gitlab.gnome.org/GNOME/orca/commit/500d4ca4a984b17dcf3e83d4fa796ac62b9cae45

That said, MATE 1.23 implements a workaround specifically for Orca (personally I disagree with that approach but whatever): 
https://github.com/mate-desktop/mate-control-center/commit/0155e265fad7655d705ca1ca9c9552d456699a3a

LM 19.2 uses MATE 1.22 though, so for LM 19.2 the ball remains in Clem's court, although it's not like this really matters because it does not impact functionality in any way.
